### ISSUE TITLE
Github ActionsのNote

### ISSUE THREAD

**Issue by sunakan** [sunakan/aws-cost#5]
```
name: Hello, World!
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
```

**Comment by sunakan** [comment]
`on: push` は、pushするたび実行するっぽい

**Comment by sunakan** [comment]
```
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
```

**Comment by sunakan** [comment]
```
- run: echo ${{ secrets.GITHUB_TOKEN }}
```

<img width="302" alt="スクリーンショット 2019-10-15 21 21 50" src="https://user-images.githubusercontent.com/43210698/66831066-d9824380-ef91-11e9-8c10-adbf1b668f9e.png">

**Comment by sunakan** [comment]
echo 大事なものはちゃんと防げる！！

**Comment by sunakan** [comment]
```
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
```
